# Generated by Django 3.2 on 2021-05-15 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=50)),
                ('pincode', models.IntegerField()),
                ('email', models.CharField(max_length=200)),
                ('storage', models.IntegerField()),
                ('rate', models.IntegerField()),
                ('available', models.IntegerField()),
                ('hours', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_ID', models.IntegerField()),
                ('vendor_ID', models.IntegerField()),
                ('transporter_ID', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('hours', models.IntegerField()),
                ('status', models.IntegerField()),
                ('SOS', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=50)),
                ('pincode', models.IntegerField()),
                ('email', models.CharField(max_length=200)),
                ('storage', models.IntegerField()),
                ('rate', models.IntegerField()),
                ('available', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Transporter',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=50)),
                ('pincode', models.IntegerField()),
                ('email', models.CharField(max_length=200)),
                ('avail_tanker', models.IntegerField()),
                ('capacity', models.IntegerField()),
                ('total_tanker', models.IntegerField()),
            ],
        ),
    ]
